INSERT INTO `gws`.`service_api_info` (`id`, `api_name`, `api_chinesename`, `version`, `application`, `interfacename`, `method`, `explain`, `reqmode`, `status`, `oauth_status`, `limit_callcounts`, `date_created`, `created_by`, `date_updated`, `updated_by`) VALUES ('47', 'setAddApplyFirst', '添加拟设立-第一步', '1.0.0', 'cas', 'com.msjf.finance.cas.facade.organ.OrganServiceFacade', 'setAddApplyFirst', '添加拟设立-第一步', 'post', 'Y', 'oauth', NULL, '2019-01-07 22:29:39', '未知', '2019-01-07 22:29:39', '未知');

INSERT INTO `gws`.`service_api_info` (`id`, `api_name`, `api_chinesename`, `version`, `application`, `interfacename`, `method`, `explain`, `reqmode`, `status`, `oauth_status`, `limit_callcounts`, `date_created`, `created_by`, `date_updated`, `updated_by`) VALUES ('48', 'setAddApplySecond', '添加拟设立-第二步', '1.0.0', 'cas', 'com.msjf.finance.cas.facade.organ.OrganServiceFacade', 'setAddApplySecond', '添加拟设立-第二步', 'post', 'Y', 'oauth', NULL, '2019-01-07 22:29:39', '未知', '2019-01-07 22:29:39', '未知');

INSERT INTO `gws`.`service_api_info` (`id`, `api_name`, `api_chinesename`, `version`, `application`, `interfacename`, `method`, `explain`, `reqmode`, `status`, `oauth_status`, `limit_callcounts`, `date_created`, `created_by`, `date_updated`, `updated_by`) VALUES ('49', 'setAddApplyThirdly', '添加拟设立-第三步', '1.0.0', 'cas', 'com.msjf.finance.cas.facade.organ.OrganServiceFacade', 'setAddApplyThirdly', '添加拟设立-第三步', 'post', 'Y', 'oauth', NULL, '2019-01-07 22:29:39', '未知', '2019-01-07 22:29:39', '未知');

INSERT INTO `gws`.`service_api_info` (`id`, `api_name`, `api_chinesename`, `version`, `application`, `interfacename`, `method`, `explain`, `reqmode`, `status`, `oauth_status`, `limit_callcounts`, `date_created`, `created_by`, `date_updated`, `updated_by`) VALUES ('50', 'setAddApplyFourthly', '添加拟设立-第四步-其它信息', '1.0.0', 'cas', 'com.msjf.finance.cas.facade.organ.OrganServiceFacade', 'setAddApplyFourthly', '添加拟设立-第四步-其它信息', 'post', 'Y', 'oauth', NULL, '2019-01-07 22:29:39', '未知', '2019-01-07 22:29:39', '未知');

INSERT INTO `gws`.`service_api_info` (`id`, `api_name`, `api_chinesename`, `version`, `application`, `interfacename`, `method`, `explain`, `reqmode`, `status`, `oauth_status`, `limit_callcounts`, `date_created`, `created_by`, `date_updated`, `updated_by`) VALUES ('51', 'getOrganInfoList', '查询企业设立列表信息', '1.0.0', 'cas', 'com.msjf.finance.cas.facade.organ.OrganServiceFacade', 'getOrganInfoList', '查询企业设立列表信息', 'post', 'Y', 'oauth', NULL, '2019-01-07 22:29:39', '未知', '2019-01-07 22:29:39', '未知');

INSERT INTO `gws`.`service_api_info` (`id`, `api_name`, `api_chinesename`, `version`, `application`, `interfacename`, `method`, `explain`, `reqmode`, `status`, `oauth_status`, `limit_callcounts`, `date_created`, `created_by`, `date_updated`, `updated_by`) VALUES ('52', 'setDeleteOrgan', '删除未提交确认设立的企业设立信息', '1.0.0', 'cas', 'com.msjf.finance.cas.facade.organ.OrganServiceFacade', 'setDeleteOrgan', '删除未提交确认设立的企业设立信息', 'post', 'Y', 'oauth', NULL, '2019-01-07 22:29:39', '未知', '2019-01-07 22:29:39', '未知');

COMMIT;